Django-Flask-Examples/RunnkoVenv/Projects/SiteCore/HomePage/urls.py
from django.conf.urls import include, url

urlpatterns = [
    url(r'^$', 'HomePage.views.index'),
    url(r'^captcha/', include('captcha.urls')),
    url(r'contacts/$', 'HomePage.views.contact'),
]

Django-Flask-Examples/RunnkoVenv/Projects/SiteCore/SiteCore/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^accounts/', include('UserRegistration.urls')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^', include('HomePage.urls')),
    url(r'^admin/', include(admin.site.urls)),
]

Django-Flask-Examples/RunnkoVenv/Projects/SiteCore/UserRegistration/urls.py
from django.conf.urls import patterns, include, url
from .views import *
from django.contrib.auth.views import password_reset

urlpatterns = patterns('',
    url(r'register/$','UserRegistration.views.register'),
    url(r'login/$', 'django.contrib.auth.views.login', {'template_name': 'login.html'}),
    url(r'logout/$', 'django.contrib.auth.views.logout', {'template_name': 'logout.html'}),
    url(r'profile/$', 'UserRegistration.views.profile_info'),
    url(r'profile/edit/$', 'UserRegistration.views.profile_update'),
    url(r'password/reset/$',
        'django.contrib.auth.views.password_reset',
        {'post_reset_redirect' : '/accounts/password/reset/done/'},
        name="password_reset"),
    (r'password/reset/done/$',
        'django.contrib.auth.views.password_reset_done'),
    (r'password/reset/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$',
        'django.contrib.auth.views.password_reset_confirm',
        {'post_reset_redirect' : '/accounts/password/done/'}),
    (r'password/done/$',
        'django.contrib.auth.views.password_reset_complete'),
)

Django-Flask-Examples/RunnkoVenv/Projects/SiteCore/UserRegistration/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User
'''
Собственно есть 2, известных мне, способа сделать Профиль пользователя и
Личный кабинет: Наследовать класс User и делать свой кастомный класс,
получая при этом возможность всех характерных команд для юзера типа
User.request или же добавлять OneToOne связь в класс профиля как ниже.
Лично мне этот способ кажется удобней.
'''
class UserProfile(models.Model):
    user = models.OneToOneField(User)# Связывает таблицы Юзера и Профиля
    # Два обязательных параметра Юзера помимо Email/Login/Password
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    '''
    Ниже демонстрация как можно сделать 2 типа аккаунта, если вам
    нужно разделить пользователей по функционалу, но вы не хотите
    использовать группы, честно говоря я не знаю зачем нужны группы.
    '''
    PROFILE_CHOICES = (
            ('RC', 'Recruiter'),
            ('CT', 'Candidate'),
            )
    profileType = models.CharField(max_length=255, choices = PROFILE_CHOICES)

'''
Магическая функция, которую я нашел на просторах интернета,
создает профиль пользователя если его не существует,
в любом случае вернет вам профиль.
Подробнее на ангельском про то что делает эта функция можете узнать тут:
http://www.codekoala.com/posts/quick-django-tip-user-profiles/
'''
User.profile = property(lambda u: UserProfile.objects.get_or_create(user=u)[0])

Django-Flask-Examples/RunnkoVenv/Projects/SiteCore/UserRegistration/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserProfile

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password',)

    def clean_email(self):
        email = self.cleaned_data.get('email')
        username = self.cleaned_data.get('username')
        if email and User.objects.filter(email=email).exclude(username=username).count():
            raise forms.ValidationError(u'Email addresses must be unique.')
        return email

class UserProfileForm(forms.ModelForm):

    class Meta:
        model = UserProfile
        fields = ('first_name', 'last_name', 'profileType', )

Django-Flask-Examples/RunnkoVenv/Projects/SiteCore/UserRegistration/views.py
# -*- coding: utf-8 -*-
from django.http import HttpResponse, HttpResponseRedirect
from django.template import RequestContext
from django.shortcuts import render, render_to_response, get_object_or_404
from django.contrib.auth import authenticate,login
from django.contrib.auth.decorators import login_required
from annoying.decorators import render_to
from django.contrib.auth import logout
from django.contrib.auth.models import User
from .forms import UserForm,UserProfileForm
from .models import UserProfile
from django.core.context_processors import csrf

def register(request):
    registered = False
    if request.method == 'POST':
        # Берем две формы и отправляем их для заполнения
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)
        # Если все поля проходят валидацию, то переходим к сохранению данных
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            '''
            Зачем нужен commit=False?
            That's useful when you get most of your model data from a
            form, but need to populate some null=False fields with
            non-form data.
            Saving with commit=False gets you a model object, then you
            can add your extra data and save it.

            Создаем профиль, заполняем, добавляем связь с юзером и потом
            сохраняем данные, а также завершаем регистрацию.
            '''
            profile = profile_form.save(commit=False)
            profile.user = user

            profile.save()
            registered = True
        else:
            print(user_form.errors, profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    return render(request,
            'registration_form.html',
            {'user_form': user_form, 'profile_form': profile_form, 'registered': registered} )


def user_login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect('/')
            else:
                return HttpResponse("Your account is disabled.")
        else:
            print("Invalid login details: {0},{1}".format(username,password))
            return HttpResponse("Invalid login details supplied.")
    else:
        return render(request, 'login.html')

@login_required
@render_to('edit_profile.html')
'''
Вытаскиваем форму, принадлежащую пользователю. Передаём данные и форму.
Сохраняем, если изменили всё правильно.
'''
def profile_update(request):
    if request.method == 'POST':
        form = UserProfileForm(request.POST, instance=request.user.profile)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/accounts/profile/')
    else:
        user = request.user
        profile = user.profile
        form = UserProfileForm(instance=user.profile)
    args = {}
    args.update(csrf(request))
    args['form'] = form
    return args

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect('/')

@login_required
def profile_info(request):
    return render(request, 'profile.html')

Django-Flask-Examples/RunnkoVenv/Projects/SiteCore/UserRegistration/templates/edit_profile.html
{% extends "sidebar.html" %}
{% load crispy_forms_tags %}
{% block sidebar_content %}
    <h1 class="page-header">Profile</h2>

    {% for field in form %}
        {{field.error}}
    {% endfor %}

    <form id="profile_form" action='/accounts/profile/edit/' method="post">
    {% csrf_token %}
    {{form|crispy}}
    <button id="profile_button" class="btn btn-lg btn-primary btn-block" type="submit">Update</button>
    </form>

{% endblock %}

Django-Flask-Examples/RunnkoVenv/Projects/SiteCore/UserRegistration/templates/login.html
{% extends "base.html" %}
{% block content %}
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
    <link href="{{STATIC_URL}}css/bootstrap.css" rel="stylesheet"></link>
    <link rel="stylesheet" href="{{STATIC_URL}}css/login.css"></link>
</head>
<body>
    <div class="container">

        <form class="form-signin" method="post" action="/accounts/login/">
            <h2 class="form-signin-heading">Login</h2>
            {% csrf_token %}
        <input type="text" name="username" id="inputUsername" class="form-control" placeholder="Username" required>
        <input type="password" name="password" id="inputPassword" class="form-control" placeholder="Password" required>
            <button class="btn btn-lg btn-primary btn-block" type="submit">Login</button>

        <a href="/accounts/password/reset/">Forgot password?</a>
        </form>
        </div>
</body>
</html>
{% endblock %}

Django-Flask-Examples/RunnkoVenv/Projects/SiteCore/UserRegistration/templates/profile.html
{% extends "sidebar.html" %}
{% block sidebar_content %}
<div>
        <div class="row">
        <h1 class="page-header">Profile</h1>
            <div class="col-sm-6">
                <!--left col-->
                <ul class="list-group">
                    <li class="list-group-item text-right"><span class="pull-left"><strong class="">Username</strong></span> {{user.username}}</li>
                    <li class="list-group-item text-right"><span class="pull-left"><strong class="">First name</strong></span> {{user.profile.first_name}}</li>
                    <li class="list-group-item text-right"><span class="pull-left"><strong class="">Last name</strong></span> {{user.profile.last_name}}</li>
                    <li class="list-group-item text-right"><span class="pull-left"><strong class="">Profile type</strong></span>{{user.profile.get_profileType_display}} </li>
                </ul>
                <form action='/accounts/profile/edit'><button id="button" class="btn btn-lg btn-primary btn-block" type="submit">Edit</button>
            </div>
        </div>
</div>
{% endblock %}

Django-Flask-Examples/RunnkoVenv/Projects/SiteCore/UserRegistration/templates/registration_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div id="content" class="container">
        <meta charset="UTF-8">
    <title>Account Registration</title>
</head>
<body>
    <h1>Registration</h1>
            {% if registered %}
            <strong>thank you for registering!</strong>
            <form action="/"></form>
            {% else %}

            <form id="user_form" method="post" action="/accounts/register/"
                    enctype="multipart/form-data">

                {% csrf_token %}

                {{ user_form|crispy }}
                {{ profile_form|crispy }}

            <button id="registry_button" class="btn btn-lg btn-primary btn-block" type="submit">Register</button>
            </form>
            {% endif %}
</div>
{% endblock %}